### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by ghost** [fischerling/plugin-wd#1]
Hi @fischerling  
I'm no longer maintaining omf, and would appreciate a ton if you can upgrade to [fisherman](https://github.com/fisherman/fisherman):
- Why? fisherman/fisherman#69 (comment)

Everything, including legacy plugins/themes work great with fisherman, but new content is _no_ longer compatible with oh-my-fish.

**Comment by fischerling** [comment]
@brj What do you mean?
Personally I use wd with fisherman, and it works flawless. Also there are
install instructions for both omf and fisherman in the README.

What can I do for further integration of wd into fisherman, after the index is
not used anymore?

**Comment by ghost** [comment]
@fischerling Fortunately the index is still (and will be) around until we do something new with the website, so no worries.

> What do you mean?

I'm sorry, I read "Directory navigation plugin for oh-my-fish" so I was confused ;)
