### ISSUE TITLE
Feature request/parity: Allow `wd add` without warp name (use current directory name)

### ISSUE THREAD

**Issue by Cretezy** [fischerling/plugin-wd#14]
I was the original author of this feature for the zsh `wd` version, but basically:

If I'm inside `~/aaa/bbb/ccc` and run `wd add`, it should add a warp called `ccc`.

If you like, I can likely provide an implementation. Thanks!

**Comment by fischerling** [comment]
I will happily accept your implementation :)

If you need help or feedback just reach out to me.

**Comment by Cretezy** [comment]
Took a while, but it's done! #15
